services:
  - type: web
    name: telegram-click-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: "PASTE_YOUR_TELEGRAM_BOT_TOKEN_HERE"
